###
GET http://localhost:3004/

###
GET http://localhost:3004/list/location HTTP/1.1

###
GET http://localhost:3004/list/region HTTP/1.1
###
GET http://localhost:3004/list/name HTTP/1.1


###
GET http://localhost:3004/count HTTP/1.1

###
GET http://localhost:3004/search?king=Robb Stark HTTP/1.1

###
GET http://localhost:3004/search?location=Riverrun&year=300 HTTP/1.1
